### ISSUE TITLE
docker-compose example

### ISSUE THREAD

**Issue by tobiasmuecksch** [nats-io/nats-docker#27]
Hey guys,
I'm missing an example for docker-compose.
Especially on how to set a custom configuration file. I haven't found out yet, how to do that.

**Comment by wallyqs** [comment]
Hi, here you can find an example of setting a cluster using Docker Compose: https://github.com/nats-io/docs/blob/a27d9248fa14688f6be7a0ac9bf25744cab58a5a/nats_docker/README.md#creating-a-nats-cluster-with-docker-compose

**Comment by wallyqs** [comment]
Here is an example of using a custom configuration file with volumes using Docker Compose. 

- First create a network and config file, for example:

```sh
docker network create nats

mkdir config
echo '
debug = true
trace = true
' > config/nats.conf
```

Then point within the compose file to point to that file:

```yaml
version: "3"
services:
  nats:
    image: nats
    command: "-c /etc/nats/nats.conf --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    volumes:
       - ./config/:/etc/nats
networks:
  default:
    external:
      name: nats
```

Use multiple replicas by using `scale` parameter:

```sh
docker-compose -f docker-compose.yaml up --scale nats=3
```
